version: "3.8"

services:
  payments-api:
    build:
      context: ./services/fs-payments-api
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    ports:
      - 3000:3000
    command: 'yarn start'
    container_name: payments-api

  database:
    build:
      context: ./services/fs-database
    container_name: database
    environment:
      POSTGRES_USER: "&&DATABASE_USER&&"
      POSTGRES_PASSWORD: "&&DATABASE_PW&&"
      DB_NAME: "&&DATABASE_NAME&&"
      POSTGRES_DB: "&&DATABASE_NAME&&"
      PGPORT: "&&DATABASE_PORT&&"
    volumes:
      - ./services/fs-database/data:/var/lib/postgresql/data