version: "3.8"

services:
  payments-api:
    build:
      context: ./services/fs-payments-api
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    ports:
      - 3000:3000
    command: 'yarn dev'
    container_name: payments-api
    volumes:
      - ./packages/fs-common:/app/node_modules/@chrishontoir/fs-common
      - ./services/fs-payments-api/src:/app/src
      - ./node_modules:/app/node_modules

  database:
    build:
      context: ./services/fs-database
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "finance_system_db"
      POSTGRES_DB: finance_system_db
      PGPORT: 5432
    volumes:
      - ./services/fs-database/data:/var/lib/postgresql/data