version: "3.8"

services:
  payments-api:
    build:
      context: ./services/payments-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: 'yarn dev'
    container_name: payments-api
    volumes:
      - ./services/payments-api/src:/app/src
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "finance_system_db"
      POSTGRES_DB: finance_system_db
      PGPORT: 5432
    volumes:
      - ./services/database/data:/var/lib/postgresql/data