version: "3.8"

services:
  payments-api:
    build:
      context: ./services/payments-api
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: 'yarn dev'
    container_name: payments-api
    volumes:
      - ./services/payments-api/src:/app/src