version: "3.8"

services:
  payments-api:
    build:
      context: ./services/payments-api
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    ports:
      - 3000:3000
    command: 'yarn start'
    container_name: payments-api

  database:
    build:
      context: ./services/database
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_NAME: "finance_system_db"
      POSTGRES_DB: finance_system_db
      PGPORT: 5432
    volumes:
      - ./services/database/data:/var/lib/postgresql/data